// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx50_fL-tR8d36tSPODa3VeKi9AELht_4',
    appId: '1:803869396086:web:07dba707fde789301e2357',
    messagingSenderId: '803869396086',
    projectId: 'passport-automation-6b3b9',
    authDomain: 'passport-automation-6b3b9.firebaseapp.com',
    storageBucket: 'passport-automation-6b3b9.firebasestorage.app',
    measurementId: 'G-M4KGPB6QDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuSrU1P7Xd9Sm6yIuyeOfIWGrktom7RGM',
    appId: '1:803869396086:android:b9ba49796c4983d71e2357',
    messagingSenderId: '803869396086',
    projectId: 'passport-automation-6b3b9',
    storageBucket: 'passport-automation-6b3b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYa10c0TtDA7tXxlJY9Cqtw7MquHITJf8',
    appId: '1:803869396086:ios:e407c11712992c1c1e2357',
    messagingSenderId: '803869396086',
    projectId: 'passport-automation-6b3b9',
    storageBucket: 'passport-automation-6b3b9.firebasestorage.app',
    iosBundleId: 'com.example.goatmitra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhqnA7Hk9uixiWpRY9HN7Xphzbz4QQQyM',
    appId: '1:130357781047:ios:480d0d9e463f3b279015b2',
    messagingSenderId: '130357781047',
    projectId: 'user-19315',
    storageBucket: 'user-19315.appspot.com',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0tGZA2vG8HQZIFxcCCW0_7tA0HWnKYqE',
    appId: '1:130357781047:web:afc80c4a30174d279015b2',
    messagingSenderId: '130357781047',
    projectId: 'user-19315',
    authDomain: 'user-19315.firebaseapp.com',
    storageBucket: 'user-19315.appspot.com',
    measurementId: 'G-NQBLFE1224',
  );
}